#!/bin/bash
mkdir -p bin
ghc --make -O3 -outputdir bin -fforce-recomp -rtsopts -static -optl-static -optl-pthread -Wall -Werror -o bin/Skynet MyBot || exit 1
cp bin/Skynet tools/Skynet
cp bin/Skynet MyBot
strip -s MyBot
zip Skynet.zip MyBot MyBot.ss
