#!/bin/bash
#ghc --make -O3 -outputdir bin -fforce-recomp -rtsopts -prof -auto -Wall -Werror -o bin/Skynet Skynet || exit 1
ghc --make -O3 -outputdir bin -fforce-recomp -rtsopts -Wall -Werror -o bin/Skynet Skynet || exit 1
