#!/bin/bash
./compile || exit 1
cd tools
./playgame.py \
 -m maps/example/tutorial1.map \
 ../bin/Skynet \
 "python sample_bots/python/HunterBot.py" \
 --turns 200 \
 -e --verbose --log_dir game_logs

